# Generated by Django 3.2.20 on 2023-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceClass', models.CharField(choices=[('l1', 'Л/1Э'), ('l2', 'Л/1У'), ('l3', 'Л/1Л'), ('k1', 'К/2К '), ('k2', 'К/2У'), ('p1', 'П/3Б'), ('p2', 'П/3Э')], max_length=2)),
                ('departureDate', models.DateField(blank=True, default=None, null=True)),
                ('departureStation', models.CharField(max_length=64)),
                ('arrivalStation', models.CharField(max_length=64)),
                ('totalDistance', models.PositiveIntegerField()),
                ('seatNumber', models.PositiveIntegerField()),
                ('trainNumber', models.CharField(max_length=64)),
                ('costTicket', models.DecimalField(decimal_places=10, max_digits=10)),
                ('costPlatzcard', models.DecimalField(decimal_places=10, max_digits=10)),
                ('costService', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
