# Generated by Django 3.2.20 on 2023-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0002_auto_20230715_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='serviceClass',
            field=models.CharField(max_length=16),
        ),
    ]
